# Generated by Django 5.0.6 on 2024-06-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Usertype',
            new_name='usertype',
        ),
    ]
